const eventos = [
    {
        id: "0001",
        titulo: "CA7RIEL & PACO AMOROSO",
        lugar: "Estadio Obras",
        ciudad: "CABA",
        fecha: "2022-12-23",
        hora: "9:00PM",
        categoria: "Conciertos",
        edad_minima: "A partir de los 7 Años",
        direccion: " Av. del Libertador 7395",
        img: "",
        descripcion:  "",
        etapa_venta: "PREVENTA - Hasta agotar stock",
        ubicacion: "CAMPO",
        precio: "$4.500",
        legal: "",
        mas_info: "https://youtu.be/64r03gcbS1A",
    },
    {
        id: "0002",
        titulo: "CONCIERTO UNICEF - HORACIO LAVANDERA - TEATRO COLÓN",
        lugar: "Teatro Colón",
        ciudad: "CABA",
        fecha: "2022-11-28",
        hora: "8:00PM",
        categoria: "Conciertos",
        edad_minima: "",
        direccion: "Cerrito 628",
        img: "afd",
        descripcion:  "",
        ubicacion: "Palco Bajo Centro",
        precio: "$8500 ",
        legal: "",
        mas_info: "",
    },
    {
        id: "0003",
        titulo: "LA NOCHE DE LAS BODEGAS",
        lugar: "Puerto Madero",
        ciudad: "CABA",
        fecha: "2022-12-15",
        hora: "7:00PM",
        categoria: "Exposiciones",
        edad_minima: "18 años",
        direccion: "",
        img: "",
        descripcion:  "",
        ubicacion: "General",
        precio: "$3.980",
        legal: "",
        mas_info: "",
    },
    {
        id: "0004",
        titulo: "FUERZA BRUTA WAYRA EN SANTA FE",
        lugar: "Estacion Belgrano",
        ciudad: "Santa Fe",
        fecha: "2023-03-09",
        hora: "9:30PM",
        categoria: "Conciertos",
        edad_minima: "ATP",
        direccion: "Blvd. Gálvez 1150, Santa Fe",
        img: "",
        descripcion:  "",
        ubicacion: "",
        precio: "",
        legal: "",
        mas_info: "https://youtu.be/FYszthdJU8c",
    },
    {
        id: "0005",
        titulo: "ABEL PINTOS EN MAR DEL PLATA",
        lugar: "Teatro Tronador",
        ciudad: "Mar del Plata",
        fecha: "",
        hora: "9:00PM",
        categoria: "Conciertos",
        edad_minima: "A partir de los 3 Años",
        direccion: "Santiago del Estero 1746",
        img: "",
        descripcion:  "",
        ubicacion: "Platea",
        precio: "$8.000",
        legal: "",
        mas_info: "https://youtu.be/opUkzmzTLuA ",
    },
    {
        id: "0006",
        titulo: "RATA BLANCA - QUILMES",
        lugar: "Estadio Centenario Quilmes",
        ciudad: "Quilmes",
        fecha: "2022-12-10",
        hora: "8:00PM",
        categoria: "Conciertos",
        edad_minima: "7 años",
        direccion: "Vicente López y Esquiú",
        img: "",
        descripcion:  "",
        ubicacion: "Campo",
        precio: "$4.000",
        legal: "",
        mas_info: "",
    },
    {
        id: "0007",
        titulo: "FIESTA EN EL JARDIN",
        lugar: "Sala 3",
        ciudad: "CABA",
        fecha: "",
        hora: "",
        categoria: "Teatro",
        edad_minima: "",
        direccion: "Sarmiento 1551",
        img: "",
        descripcion:  "",
        ubicacion: "General",
        precio: "$1.000",
        legal: "",
        mas_info: "",
    },
    {
        id: "0008",
        titulo: "PALITO ORTEGA",
        lugar: "Teatro Colonial",
        ciudad: "Avellaneda",
        fecha: "2022-12-09",
        hora: "9:00PM",
        categoria: "Conciertos",
        edad_minima: "",
        direccion: " Av. Bartolomé Mitre 141",
        img: "",
        descripcion:  "",
        ubicacion: "Palcos",
        precio: "$15000 ",
        legal: "",
        mas_info: "",
    },
];


